
services:
  frontend:
    image: node:20-alpine
    container_name: kyskfilms_frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
